### ISSUE TITLE
Remove legacy doc-label-check action

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar-test-infra#57]
We've switched to docbot. It should be safe to delete doc-label-check.

**Comment by tisonkun** [comment]
If we're assuming there're other projects using it, we should publish a tag and remove it in master.

**Comment by maxsxu** [comment]
Yes, the legacy docbot should be removed. I'll send a PR later.
AFAIK, only the main pulsar repo uses the docbot.

**Comment by nodece** [comment]
I don't suggest that you remove this code. Could we make a deprecated tag?

**Comment by tisonkun** [comment]
@nodece as I mentioned above, if we're assuming there're other projects using it, we should publish a tag and remove it in master.

For example, we push a tag `v0.1.0` so that users depend on `doc-label-check` can write `apache/pulsar-test-infra/doc-label-check@v0.1.0`.

We don't effectively maintain it, though.
