### ISSUE TITLE
Use Docker container action for docbot

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar-test-infra#58]
https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

I don't know why we use composition and leave the [docbot workflow](https://github.com/apache/pulsar/blob/fb0f653eadcf6bf72eb8c8efcc29975da6e21267/.github/workflows/ci-documentbot.yml) checkout source code and setup golang.

We can make the use experience like pulsarbot action.

cc @maxsxu

**Comment by tisonkun** [comment]
See also https://github.com/tisonkun/pulsar-test-infra/tree/docker-action for a prototype, the docker image size is 12.9MB.

**Comment by michaeljmarshall** [comment]
I agree with moving this to a docker action.

**Comment by maxsxu** [comment]
The main reason for using composite instead of docker initially was the speed of execution, as the latency to build and retrieve the container.

> I don't know why we use composition and leave the [docbot workflow](https://github.com/apache/pulsar/blob/fb0f653eadcf6bf72eb8c8efcc29975da6e21267/.github/workflows/ci-documentbot.yml) checkout source code and setup golang.

We can also try to put these steps into the composite action itself.

**Comment by tisonkun** [comment]
Download an image with 12.9MB may be faster than setting up go environment. We can give it a try.

**Comment by maxsxu** [comment]
@tisonkun  You have raised a very valuable question. I do curious about the real performance between composite action and docker action. So I did a quick test and the results show that composite action takes only about half the execution time of docker action.

- [Comparison](https://github.com/open-github/pulsar/actions/workflows/ci-documentbot.yml) as shown below:

> <img width="925" alt="image" src="https://user-images.githubusercontent.com/15963141/186450802-7b95a180-6ee5-4f19-8653-697846bbc1de.png">
 
- [Details of composite action](https://github.com/open-github/pulsar/runs/7995320623?check_suite_focus=true):

> <img width="611" alt="image" src="https://user-images.githubusercontent.com/15963141/186451495-04591dfd-e813-4896-9465-de000309847b.png">

- [Details of docker action:](https://github.com/open-github/pulsar/runs/7997522614?check_suite_focus=true)

> <img width="611" alt="image" src="https://user-images.githubusercontent.com/15963141/186451851-c94ea119-7076-41b7-a129-003a8dc0468d.png">

For short operations like labeling, we need to run our action quickly. So execution speed is the primary requirement.

**Comment by tisonkun** [comment]
Cool! Then I'll close this issue as won't do.

Although, we can still try to let the docbot action to be used as barely `apache/pulsar-test-infra/docbot@main`.

**Comment by maxsxu** [comment]
> Although, we can still try to let the docbot action to be used as barely `apache/pulsar-test-infra/docbot@main`.

Yes, one thing we can be sure of now is to simplify the current ci-documentbot.yaml workflow file like this https://github.com/open-github/pulsar/blob/master/.github/workflows/ci-documentbot.yml.  which is both applicable for whether composite or docker.

This will send PR in both pulsar-test-infra and pulsar repo.
