### ISSUE TITLE
[docbot] Cannot to label for PR correctly

### ISSUE THREAD

**Issue by nodece** [apache/pulsar-test-infra#59]
<img width="1461" alt="image (2)" src="https://user-images.githubusercontent.com/16235121/184477262-a02197c7-162d-40b5-b4ac-e86d9ffaf2ce.png">

**Comment by tisonkun** [comment]
cc @maxsxu 

@nodece if you can provide concrete reproduce steps, we may investigate the root cause more accurate.

**Comment by tisonkun** [comment]
Related trace: https://github.com/apache/pulsar/runs/7816260130?check_suite_focus=true

It seems the content analyze part is correct.

**Comment by nodece** [comment]
This log looks confused.  

I have a few questions:
- What are `Issue labels`? Is it equal to `PR labels`? 
- Why do the issue labels miss the `doc-label-missing`?

I think there is something wrong with the diff labels.

**Comment by nodece** [comment]
> if you can provide concrete reproduce steps, we may investigate the root cause more accurate.

I'm not sure when happened.

**Comment by nodece** [comment]
I noticed the following code. Why are different types distinguished? I think all four types should be used the same way for labeling. 

```
func (a *Action) Run(actionType string) error {
	a.event = actionType
	switch actionType {
	case "opened", "edited":
		return a.onPullRequestOpenedOrEdited()
	case "labeled", "unlabeled":
		return a.onPullRequestLabeledOrUnlabeled()
	}
	return nil
}
```

**Comment by maxsxu** [comment]
> I noticed the following code. Why are different types distinguished? I think all four types should be used the same way for labeling.

The different handling strategies for the opened/edited and labeled/unlabeled events are intended to achieve different results.

- For the opened/edited events, we want the PR to be labeled correctly.
- For the labeled/unlabled events, we want the corresponding label task list in the PR Body to be checked correctly

**Comment by nodece** [comment]
Assuming that the opened event and the labeled event occur sequentially, if opened event action is not completed, then starting the labeled event action, the opened event is cancelled, this PR cannot labeling correctly.

**Comment by nodece** [comment]
Met again:
```
[INFO] 2022/08/27 08:45:24 @List issue labels
[INFO] 2022/08/27 08:45:24 Issue labels: [type/improvement component/security release/2.9.4 release/2.11.1 release/2.10.3]
[INFO] 2022/08/27 08:45:24 @List current labels
[INFO] 2022/08/27 08:45:24 Current labels: []
[INFO] 2022/08/27 08:45:24 @List expected labels
[INFO] 2022/08/27 08:45:24 Expected labels: map[doc-not-needed:true]
[INFO] 2022/08/27 08:45:24 Labels to remove: map[]
[INFO] 2022/08/27 08:45:24 @Add missing label
[FATAL] 2022/08/27 08:45:25 /home/runner/work/pulsar/pulsar/docbot/main.go:630: Please provide a correct documentation label for your PR.
Instructions see [Pulsar Documentation Label Guide](https://docs.google.com/document/d/1Qw7LHQdXWBW9t2-r-A7QdFDBwmZh6ytB4guwMoXHqc0).
```

https://github.com/apache/pulsar/pull/16815
