### ISSUE TITLE
[pulsarbot] Bot should not comment on closed/merged PRs

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar-test-infra#73]
I noticed the Pulsar Bot comment on old PRs that have either been merged or closed. I don't think we should have the bot updating those old PRs since it just creates unnecessary notifications for contributors.

I'm not able to help add this feature. This issue is just meant to start a conversation.

**Comment by nodece** [comment]
This is a good catch! Currently, the `docbot` adds a doc label based on the PR description, when the PR description is incorrect, we still add a comment.

**Note:** For the doc label, we can only change the PR description, and then the `docbot` will check this and do the labeling.

I have an idea, if the PR description is incorrect and the state is merged or closed, we will no longer add a comment.

**Comment by tisonkun** [comment]
> I have an idea, if the PR description is incorrect and the state is merged or closed, we will no longer add a comment.

Yes. Check the PR state in the bot or filter out in the workflow is OK.
